# Required
version: 2

# Set the conda virenv
conda:
  environment: env_cpu.yml


# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

# build package
python:
  version: 3.9
  install:
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
